### ISSUE TITLE
A problem with your atom.xml

### ISSUE THREAD

**Issue by yujiangshui** [hemanth/nmotw.in#13]
I use the atom.xml to subscribe your blog, but the post permalinks are start with http://hemanth.github.io/nmotw.in/ not the domain http://nmotw.in/. And this will cause a problem that when I open your post through RSS reader, the post cannot find JS and CSS files.

**Comment by hemanth** [comment]
@yujiangshui Thanks for reporting this. [atom.xml#L8](https://github.com/hemanth/nmotw.in/blob/master/source/atom.xml#L8) needs a fix, will be doing it soon.

**Comment by hemanth** [comment]
Fixed it, but have over wrote the site with old entires duh! I'm far away from the machine that has the day, will be up by EOD.
