### ISSUE TITLE
tourism

### ISSUE THREAD

**Issue by goloroden** [hemanth/nmotw.in#14]
[tourism](https://github.com/thenativeweb/tourism) is a convenience wrapper around Grunt that greatly simplifies how you write a `Gruntfile.js`.

It abstracts away the complexity of Grunt by making opinionated choices for you, e.g. what code analysis tool to use and how it should be configured. So instead of needing to work it out all for yourself, you can simply tell tourism which code to analyze. The same is true for testing, releasing, updating dependencies, and so on…

With tourism, a `Gruntfile.js` that runs code analysis and unit tests looks as easy as:

``` javascript
'use strict';

var tourism = require('tourism');

module.exports = tourism({
  analyse: {
    server: [ '**/*.js', '!node_modules/**/*.js' ]
  },
  test: {
    server: [ 'test/**/*.js' ]
  }
});
```

Of course you can not accomplish every possible task in the world this way. tourism needs to know how to approach what you want to do, hence it may not be the perfect choice for every thinkable build requirement.

As said: tourism has some opinionated decision in it, based on lots of best practices, and if this matches for you, you get a wonderful starting point. It is actively developed by a team who uses it regularly in > 100 Node.js modules, so if there is anything that you are missing, feel free to [create an issue](https://github.com/thenativeweb/tourism/issues), or fork and provide a pull request.

Oh, and one more thing: Maybe one day Grunt will not be the choice #1 any more, maybe it will be Gulp, or anything else. Once tourism changes the engine that's underneath, everything works as before. It's not up to _you_ to make the adaptions, because all of Grunt's (or Gulp's or whatever's) details are being abstracted away.

**Comment by hemanth** [comment]
Nice, it would be useful if you could give a comparison of this along with a [huge gruntfile](https://gist.github.com/ChrisWren/5786774) :)

**Comment by goloroden** [comment]
It doesn't make too much sense to compare it to an arbitrary `Gruntfile.js` file, because tourism needs to have support for what people want to achieve.

Hence, I added more explanation of what it is, what it wants to be, and how you can use it.

**Comment by hemanth** [comment]
:+1:
