### ISSUE TITLE
Fetchival

### ISSUE THREAD

**Issue by typicode** [hemanth/nmotw.in#17]
Hi,

fetchival is a small window.fetch wrapper. It's promise-based and you can run the same code in Node and the browser (thanks to other modules).

```javascript
var fetchival = require('fetchival')
fetchival.fetch = require('node-fetch')

fetchival('/posts')
  .get({ category: 'javascript' })
  .then(function (json) {
    console.log(json)
  })
```

https://github.com/typicode/fetchival

**Comment by hemanth** [comment]
Nice module @typicode but something similar was already covered. [isomorphic-fetch](http://nmotw.in/isomorphic-fetch/).

**Comment by typicode** [comment]
Thanks for the comment, no worries. Didn't know about isomorphic-fetch, great project :)
Yes, this is the idea making it easier and more concise to write requests using fetch.
Closing the issue.

**Comment by hemanth** [comment]
:+1:
