### ISSUE TITLE
generator-travis

### ISSUE THREAD

**Issue by iamstarkov** [hemanth/nmotw.in#23]
https://github.com/iamstarkov/generator-travis
It’s easiest way to get up-to-date travis config in your project.
And easiest way to stop worrying about travis config if you are maintaining your own custom generators, just compose generator-travis with them

**Comment by hemanth** [comment]
Nice module, but normally I plan to cover modules that are not generators.

**Comment by iamstarkov** [comment]
It's okay

On Thursday, 22 October 2015, hemanth.hm <notifications@github.com> wrote:

> Nice module, but normally I plan to cover modules that are not generators.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hemanth/nmotw.in/issues/23#issuecomment-150345633>.
>


-- 
Cheers,
Vladimir Starkov, iamstarkov.com
