### ISSUE TITLE
Smart quotes

### ISSUE THREAD

**Issue by tolmasky** [hemanth/nmotw.in#24]
Just a heads up I think Jekyll by default smart-quotes which is what's causing this example to give a syntax error: http://nmotw.in/hide-secrets/

I believe adding this to _config.yml will fix it:

kramdown:
    smart_quotes: ["apos", "apos", "quot", "quot"]

(form http://stackoverflow.com/questions/25596792/how-do-i-turn-off-smart-quotes-in-jekyll )

**Comment by hemanth** [comment]
@tolmasky Thanks for reporting! Is there something missing [here](https://github.com/hemanth/nmotw.in/blob/master/_config.yml#L98-L99) ?

**Comment by tolmasky** [comment]
Hi I was trying to reproduce this locally but when I download this repo and run jekyll serve I get:

Configuration file: /Users/tolmasky/Desktop/nmotw.in/_config.yml
       Deprecation: The 'pygments' configuration option has been renamed to 'highlighter'. Please update your config file accordingly. The allowed values are 'rouge', 'pygments' or null.

I've tried changing pigments to hight highlighter but then it just complains that pygments.rb doesn't exist or something. I'm not familiar with Ruby so I'm kind of stuck on figuring out what's going on.

**Comment by tolmasky** [comment]
So I got it working after some ruby version stuff, but I don't see hide-secrets. Is that one in a branch or something?

**Comment by tolmasky** [comment]
Oh I see you've tackled it already, is it working for you now? (I still see them as smart on the site itself).

**Comment by hemanth** [comment]
I had the same problem [here](http://h3manth.com/new/blog/2015/are-you-async-yet/) and had solved it, but can't recall the fix :/

**Comment by tolmasky** [comment]
Could you upload the hide-secrets post? I think it didn't actually make it into this commit: https://github.com/hemanth/nmotw.in/commit/92d8fe553b42ff7a1eb0432b6d5209eaa17ea7ff

**Comment by hemanth** [comment]
Deployed it still the same, strange.

**Comment by tolmasky** [comment]
Having looked into it more, the reason the smart quotes are still happening is that they are being explicitly added with rubypants. If you take out rubypants it works fine.

**Comment by hemanth** [comment]
Bingo! That reminded me of [this](http://stackoverflow.com/a/10564083) answer.

Thanks! It's fine now.
