### ISSUE TITLE
Rest your eyes

### ISSUE THREAD

**Issue by siddharthkp** [hemanth/nmotw.in#42]
rest your eyes
`Rest your eyes while your command runs`

https://github.com/siddharthkp/rest-your-eyes
Category: cli

![rest your eyes](https://raw.githubusercontent.com/siddharthkp/rest-your-eyes/master/demo-install.gif)

![rest your eyes](https://raw.githubusercontent.com/siddharthkp/rest-your-eyes/master/demo-test.gif)

**Comment by hemanth** [comment]
![filmeditor-horror-the-texas-chainsaw-massacre-chain-saw-xT9KVLa6TP28d3MhDW](https://camo.githubusercontent.com/0bd5a5dfb1df84e02b449f58c06fd82ee47720b3/68747470733a2f2f6d65646961312e67697068792e636f6d2f6d656469612f7854394b564c61365450323864334d6844572f67697068792e676966>)

**Comment by hemanth** [comment]
https://nmotw.in/rest-your-eyes/ done.
