### ISSUE TITLE
Hiper - 🚀 A statistical analysis tool for performance testing

### ISSUE THREAD

**Issue by albinekb** [hemanth/nmotw.in#59]
https://github.com/pod4g/hiper
![Image](https://camo.githubusercontent.com/247e9ab7a110bfa09c5133f7503f967995b5411d/687474703a2f2f377874396e382e636f6d322e7a302e676c622e636c6f7564646e2e636f6d2f6869706572392e706e67)

**Comment by hemanth** [comment]
https://nmotw.in/hiper/ thnx.
