### ISSUE TITLE
node-rules

### ISSUE THREAD

**Issue by mithunsatheesh** [hemanth/nmotw.in#6]
[node-rules](https://github.com/mithunsatheesh/node-rules) is a simple but effective rule engine we built on top of node.js. We developed it while we were in the process of building a transaction risk management system. :) Let me know what you think.

**Comment by hemanth** [comment]
@mithunsatheesh [Done](http://nmotw.in/node-rules/)

**Comment by mithunsatheesh** [comment]
Hey! Thanks @hemanth .

**Comment by hemanth** [comment]
:+1:
